
package com.zc.bsm.webgetservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "zhangService", targetNamespace = "http://webService.bsm.zc.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZhangService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "zhangshaofangfa", targetNamespace = "http://webService.bsm.zc.com", className = "com.zc.bsm.webservice.Zhangshaofangfa")
    @ResponseWrapper(localName = "zhangshaofangfaResponse", targetNamespace = "http://webService.bsm.zc.com", className = "com.zc.bsm.webservice.ZhangshaofangfaResponse")
    public String zhangshaofangfa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
