
package com.zc.bsm.webgetservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "zhangService", targetNamespace = "http://webService.bsm.zc.com", wsdlLocation = "http://localhost:8089/zhangshao?wsdl")
public class ZhangService_Service
    extends Service
{

    private final static URL ZHANGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8089/zhangshao?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ZHANGSERVICE_WSDL_LOCATION = url;
    }

    public ZhangService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZhangService_Service() {
        super(ZHANGSERVICE_WSDL_LOCATION, new QName("http://webService.bsm.zc.com", "zhangService"));
    }

    /**
     * 
     * @return
     *     returns ZhangService
     */
    @WebEndpoint(name = "zhangServicePort")
    public ZhangService getZhangServicePort() {
        return (ZhangService)super.getPort(new QName("http://webService.bsm.zc.com", "zhangServicePort"), ZhangService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZhangService
     */
    @WebEndpoint(name = "zhangServicePort")
    public ZhangService getZhangServicePort(WebServiceFeature... features) {
        return (ZhangService)super.getPort(new QName("http://webService.bsm.zc.com", "zhangServicePort"), ZhangService.class, features);
    }
    public static void main(String[] args) {
		ZhangService_Service s=new ZhangService_Service();
		 ZhangService zs= s.getZhangServicePort();
	String result=zs.zhangshaofangfa("张少", 16);
		 System.out.println(result);
	}
}
